### PR TITLE
ENH: Update extension metadata

### PR DESCRIPTION
**Pull request by jcfr**
Consolidate extension metadata based on the corresponding s4ext file organized
in the ExtensionsIndex repository.

### CODE REVIEW

**Comment by jcfr** [comment]
Please, could this be reviewed & merged :pray:

**Comment by jcfr** [comment]
Email sent on June 12th 2024 to @JoostJM and @che85 with @lassoan in cc:

```
Subject: Help to merge https://github.com/JoostJM/SlicerCaseIterator/pull/21

Hi Joost and Christian,

When you have a chance, we would appreciate your help to merge the following pull request:

  ENH: Update extension metadata
  https://github.com/JoostJM/SlicerCaseIterator/pull/21

Changes are trivial as they only include updates to the extension metadata.

Thanks
J-Christophe
```

**Comment by jcfr** [comment]
Follow-up email sent on June 19th 2024 to @JoostJM and @che85 with @lassoan in cc:

```
Hi Joost and Christian, 

Let us know if you need anything to move forward with the integration of the referenced pull requests.

Thanks
J-Christophe
```

**Comment by che85** [comment]
@jcfr FYI, I don't have the rights for merging.

**Comment by JoostJM** [comment]
My apologies for the late response

**Comment by jcfr** [comment]
@JoostJM  Thanks for taking the time to follow-up :pray: :rocket: 

And to quote @lassoan : 

> To relieve you from responsibilities in the future, you could consider moving this repository to the Slicer organization. You can do it in the repository settings by a few clicks.

**Pull request merged**
