### PR TITLE
ENH: Use Segment Editor instead of Editor in Case Iterator

### PR DESCRIPTION
**Pull request by cpinter**
The Editor module is considered legacy. It is already in the legacy category and does not appear in the main module list in 4.10 and will be removed from 5.0. Also, Segment Editor is considered to be a significantly more advanced version of Editor, so it makes sense to use it when doing segmentations with Slicer.

### CODE REVIEW

**Comment by JoostJM** [comment]
@cpinter Thanks for the PR, this is certainly the way to go. However, I want to add some code to recognize whether input mask is segmentation or labelmap, and in case of the latter, load it and then convert it to segmentation.

This is to allow input from, say, automatic segmentation algorithms (which will generally create labelmaps, not segmentations) to remain usable in this workflow.

**Comment by cpinter** [comment]
Makes sense. I can do it no problem. How would you decide if the file is labelmap or segmentation? Only by extension or would you try to load it and see if it was successful?


On November 8, 2018 05:47:36 Joost van Griethuysen <notifications@github.com> wrote:

@cpinter<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcpinter&data=02%7C01%7Ccsaba.pinter%40queensu.ca%7Ce17860d5fd2148d02c2108d6456796f7%7Cd61ecb3b38b142d582c4efb2838b925c%7C1%7C0%7C636772708555033675&sdata=PtY2kcFwglJ5T8vxhHVHt6nr3%2B0HJs%2BHs8kSxQks4EU%3D&reserved=0> Thanks for the PR, this is certainly the way to go. However, I want to add some code to recognize whether input mask is segmentation or labelmap, and in case of the latter, load it and then convert it to segmentation.

This is to allow input from, say, automatic segmentation algorithms (which will generally create labelmaps, not segmentations) to remain usable in this workflow.

**Comment by JoostJM** [comment]
> How would you decide if the file is labelmap or segmentation? Only by extension or would you try to load it and see if it was successful?

I think starting from just looking at extensions is fine. That would present us with a workable (though more constrained) version. From that we could enhance it in the future by looking at if it is successfull or not.

**Comment by cpinter** [comment]
I amended the commit. It seem to work fine, any labelmap (that does not have the composite .seg.nrrd extension) is loaded and imported to a segmentation, after which the labelmap is removed.

**Comment by JoostJM** [comment]
@cpinter Looks good! Thanks for the help.

**Comment by cpinter** [comment]
Thanks for merging!

**Pull request merged**
